
# @doc README.md
# ## Examples
# 
# See the following files for examples:
# 
# - `./doc/make_readme.sh`

rm README.md
echo "<!-- generated by make_readme.sh; do not edit manually -->" > README.md
g++ ./doc/make_readme.cpp -I./ -o ./tmp
./tmp
rm ./tmp
