
# @doc README.md
# ## Examples
# 
# See the following files for examples:
# 
# - `./doc/make_readme.sh`: A simple shell script which compiles a tiny c++
#   programme that in turn makes `README.md`.

rm README.md
echo "<!-- generated by ./doc/make_readme.sh; do not edit manually -->" > README.md
g++ ./doc/make_readme.cpp -I./ -o ./tmp
./tmp
rm ./tmp
